-- Grain: DDL only, no output rows.
-- Creates the four source tables described in SPEC.md. No star schema, no
-- surrogate keys, no dimension tables -- these are the tables as generated by
-- generate_data.py, loaded as-is.

DROP TABLE IF EXISTS members;
CREATE TABLE members (
    member_id       VARCHAR PRIMARY KEY,
    birth_date      DATE NOT NULL,
    sex             VARCHAR NOT NULL,       -- 'M' / 'F'
    coverage_start  DATE NOT NULL,
    coverage_end    DATE,                   -- NULL if still enrolled
    death_date      DATE,                   -- NULL if alive
    plan_id         VARCHAR NOT NULL
);

DROP TABLE IF EXISTS drug_reference;
CREATE TABLE drug_reference (
    drug_name       VARCHAR PRIMARY KEY,
    drug_class      VARCHAR NOT NULL        -- 'DIABETES' or 'STATIN'
);

DROP TABLE IF EXISTS pharmacy_fills;
CREATE TABLE pharmacy_fills (
    fill_id         VARCHAR PRIMARY KEY,
    member_id       VARCHAR NOT NULL REFERENCES members(member_id),
    drug_name       VARCHAR NOT NULL REFERENCES drug_reference(drug_name),
    fill_date       DATE NOT NULL,
    days_supply     INTEGER NOT NULL CHECK (days_supply > 0)
);

DROP TABLE IF EXISTS conditions;
CREATE TABLE conditions (
    member_id       VARCHAR NOT NULL REFERENCES members(member_id),
    condition_group VARCHAR NOT NULL,       -- 'DIABETES' / 'ASCVD' / 'HOSPICE' -- simplified stand-in for real dx code sets
    dx_date         DATE NOT NULL
);
